# Step
stages:
  - build
  - deploy

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE_NAME: registry.gitlab.com/$CI_PROJECT_PATH

# # Login Registry
# before_script:
#   - "docker login -u $GITLAB_USERNAME -p $GITLAB_TOKEN registry.gitlab.com"

# Build Image
build-image:
  stage: build
  image: node:8-alpine
  only:
    - master
  script:
    - "yarn install"
    - "yarn build"
  artifacts:
    paths:
      - dist
    expire_in: 1 week

# Deploy Development
deploy-staging:
  image: alpine
  stage: deploy
  only:
    - master
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete dist/ gitlab@sn-curtain.com:/var/www/dev.sn-curtain.com/html/
