version: '3'

services:
  sn-curtain.com-frontend-staging:
    image: registry.gitlab.com/sn-curtain/sn-curtain.com:latest
    container_name: sn-curtain.com-frontend-production
    restart: always
    ports:
      - 6000:5000
    environment:
      - NODE_ENV=production
