version: '3'

services:
  sn-curtain.com-frontend-staging:
    image: registry.gitlab.com/sn-curtain/sn-curtain.com:latest
    container_name: sn-curtain.com-frontend-staging
    restart: always
    environment:
      - NODE_ENV=staging
