version: '3'

services:
  sn-curtain.com-frontend-staging:
    container_name: sn-curtain.com-frontend-staging
    build: ../
    restart: always
    volumes:
      - /var/www/dev.sn-curtain.com/html:/home/app/sn-curtain.com
    environment:
      - NODE_ENV=staging
      