version: '3'

services:
  frontend-production:
    image: registry.gitlab.com/sn-curtain/sn-curtain.com/production:latest
    container_name: frontend-production
    restart: always
    ports:
      - 80
    volumes:
      - /home/${LINUX_USERNAME}/frontend-log/dev.sn-curtain.com:/var/log/nginx
    environment:
      - VIRTUAL_HOST=sn-curtain.com
      - VIRTUAL_PORT=80
      - NODE_ENV=production
      - BACKEND_URI=${BACKEND_URI_PROD}
      - OMISE_CLIENT=${OMISE_CLIENT}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS_PROD}
    networks:
      - application-tier

version: "3"

networks:
  application-tier: