version: '3'

services:
  frontend-staging:
    image: registry.gitlab.com/sn-curtain/sn-curtain.com/staging:latest
    container_name: frontend-staging
    restart: always
    ports:
      - 80
    volumes:
      - /home/${LINUX_USERNAME}/frontend-log/dev.sn-curtain.com:/var/log/nginx
    environment:
      - VIRTUAL_HOST=dev.sn-curtain.com
      - VIRTUAL_PORT=80
      - NODE_ENV=production
      - BACKEND_URI=${BACKEND_URI_DEV}
      - BACKEND_IP=${BACKEND_IP_DEV}
      - OMISE_CLIENT=${OMISE_CLIENT}

    networks:
      - application-tier

version: "3"

networks:
  application-tier:
  